import {
  repeatToFillSequence,
  createEmptySequence,
} from '../utils/beats.utils';
import { IBeatSequence, InstrumentType } from './tracks-editor.interface';

export const DRUM_SEQUENCES: IBeatSequence[] = [
  {
    name: 'Four on the Floor',
    instruments: {
      kick: {
        name: 'kick',
        type: InstrumentType.KICK,
        beats: repeatToFillSequence([true, false, false, false]),
      },
      snare: {
        name: 'snare',
        type: InstrumentType.SNARE,
        beats: createEmptySequence(),
      },
      openHat: {
        name: 'openHat',
        type: InstrumentType.OPEN_HAT,
        beats: createEmptySequence(),
      },
      closedHat: {
        name: 'closedHat',
        type: InstrumentType.CLOSED_HAT,
        beats: createEmptySequence(),
      },
    },
  },
  {
    name: 'Led Zeppelin: When the Levee Breaks',
    instruments: {
      kick: {
        name: 'kick',
        type: InstrumentType.KICK,
        beats: repeatToFillSequence([
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          true,
          true,
          false,
          false,
          false,
          false,
        ]),
      },
      snare: {
        name: 'snare',
        type: InstrumentType.SNARE,
        beats: repeatToFillSequence([false, false, false, false, true]),
      },
      openHat: {
        name: 'openHat',
        type: InstrumentType.OPEN_HAT,
        beats: repeatToFillSequence([true, false]),
      },
      closedHat: {
        name: 'closedHat',
        type: InstrumentType.CLOSED_HAT,
        beats: createEmptySequence(),
      },
    },
  },
  {
    name: 'James Brown: Funky President',
    instruments: {
      kick: {
        name: 'kick',
        type: InstrumentType.KICK,
        beats: [
          true,
          false,
          false,
          true,
          false,
          false,
          false,
          true,
          false,
          true,
          true,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      snare: {
        name: 'snare',
        type: InstrumentType.SNARE,
        beats: [
          true,
          false,
          false,
          true,
          false,
          false,
          false,
          true,
          false,
          true,
          true,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      openHat: {
        name: 'openHat',
        type: InstrumentType.OPEN_HAT,
        beats: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      closedHat: {
        name: 'closedHat',
        type: InstrumentType.CLOSED_HAT,
        beats: [
          true,
          false,
          true,
          false,
          true,
          false,
          true,
          false,
          true,
          false,
          false,
          false,
          true,
          false,
          true,
          false,
        ],
      },
    },
  },
];

export const EMPTY_SEQUENCE: IBeatSequence = {
  name: 'Custom',
  instruments: {
    kick: {
      name: 'kick',
      type: InstrumentType.KICK,
      beats: createEmptySequence(),
    },
    snare: {
      name: 'snare',
      type: InstrumentType.SNARE,
      beats: createEmptySequence(),
    },
    openHat: {
      name: 'openHat',
      type: InstrumentType.OPEN_HAT,
      beats: createEmptySequence(),
    },
    closedHat: {
      name: 'closedHat',
      type: InstrumentType.CLOSED_HAT,
      beats: createEmptySequence(),
    },
  },
};
