import {
  repeatToFillSequence,
  createEmptySequence,
} from '../utils/beats.utils';

export const DRUM_SEQUENCES = [
  {
    name: 'Four on the Floor',
    instruments: {
      kick: repeatToFillSequence([true, false, false, false]),
      snare: createEmptySequence(),
      openHat: createEmptySequence(),
      closedHat: createEmptySequence(),
    },
  },
  {
    name: 'Led Zeppelin: When the Levee Breaks',
    instruments: {
      kick: repeatToFillSequence([
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
      ]),
      snare: repeatToFillSequence([false, false, false, false, true]),
      openHat: repeatToFillSequence([true, false]),
      closedHat: createEmptySequence(),
    },
  },
  {
    name: 'James Brown: Funky President',
    instruments: {
      kick: [
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
      ],
      snare: [
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
      ],
      openHat: [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
      ],
      closedHat: [
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
      ],
    },
  },
];
