import {
  repeatToFillSequence,
  createEmptySequence,
} from '../utils/beats.utils';
import { IBeatSequence } from './tracks-editor.interface';

export const DRUM_SEQUENCES: IBeatSequence[] = [
  {
    name: 'Four on the Floor',
    instruments: {
      kick: {
        name: 'kick',
        beats: repeatToFillSequence([true, false, false, false]),
      },
      snare: { name: 'snare', beats: createEmptySequence() },
      openHat: { name: 'openHat', beats: createEmptySequence() },
      closedHat: { name: 'closedHat', beats: createEmptySequence() },
    },
  },
  {
    name: 'Led Zeppelin: When the Levee Breaks',
    instruments: {
      kick: {
        name: 'kick',
        beats: repeatToFillSequence([
          true,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          true,
          true,
          false,
          false,
          false,
          false,
        ]),
      },
      snare: {
        name: 'snare',
        beats: repeatToFillSequence([false, false, false, false, true]),
      },
      openHat: {
        name: 'openHat',
        beats: repeatToFillSequence([true, false]),
      },
      closedHat: {
        name: 'closedHat',
        beats: createEmptySequence(),
      },
    },
  },
  {
    name: 'James Brown: Funky President',
    instruments: {
      kick: {
        name: 'kick',
        beats: [
          true,
          false,
          false,
          true,
          false,
          false,
          false,
          true,
          false,
          true,
          true,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      snare: {
        name: 'snare',
        beats: [
          true,
          false,
          false,
          true,
          false,
          false,
          false,
          true,
          false,
          true,
          true,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      openHat: {
        name: 'openHat',
        beats: [
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          false,
        ],
      },
      closedHat: {
        name: 'closedHat',
        beats: [
          true,
          false,
          true,
          false,
          true,
          false,
          true,
          false,
          true,
          false,
          false,
          false,
          true,
          false,
          true,
          false,
        ],
      },
    },
  },
];
